language: python
python:
  - '3.5'
  - '3.6'
install: travis_wait pip install -r requirements.txt
script: travis_wait python -m unittest discover
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: BJrS1tSLQRZ/RcgraQ5v654hPFgcK47kITOJ/HhXc0+M+9EkB9PSugLTZRQvQIbXIDXqyoJ43qFXmlbHYXv6/HYzpWLofXeVWcpJ8aJXFPYe1cAUkdDJbjpVdHUVWAzXciQfvNxqxio7i2Mg1XsJnXPQ6O3YfU26cQu08m4doEbbOkZmJkGD/Ec7+ebYpSvr2nwOwt6Mwfi1DTri02Y5lUqUEzI/hLAPjT2sdzfRbBDdxYLd028QZCGU+aINAWKWkF4oYGRXMhI/IzeDQYnUp4Iag85FVhSBO4GR7toOUTgwxXkir8ngnhuvOsGi3Qgc/JakVNWstTuHYeNhJTHgqaMInoRJE5JuB67wR6UsL4XcGXyq+yg6APM33yj0NMCDabjp+tMV0bHtW2XjIoRmSlRzaN0GJLdaI7N3WY625pwcm94QV8Znc3kCcq2VyudSuKtI3nL2Jn890hzN9LYXqwyU1VZNeBGCIDhuHnEqTeWdpfg1NcpUGKl8opJ+gXniH6qD0yvAnqwDLX6Wxq++up9+MST1oVYslRa/fk/5ZML/xoLqpsBPWzqAASHg8a1xap2pol9GgCCFbRM79rg1dNqMVkOk9Q5S90X2Psv6MQtrLtQcn+AorfUHl+ePv2w2aow47IhRtptChHHsllNqYQhwr8Tdu/PIIin4hhUnBVk=
